---
kind: pipeline
name: default-linux-amd64

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    pull: default
    image: rancher/dapper:v0.5.8
    environment:
      OAUTH_TOKEN:
        from_secret: github_token
    commands:
      - dapper -f Dockerfile.dapper ci
    privileged: true
    volumes:
      - name: docker
        path: /var/run/docker.sock
    when:
      event:
        - push
        - pull_request

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

trigger:
  event:
    exclude:
      - promote